/**
 * Express Server for MARIA CODE API
 * With Rate Limiting and API Endpoints
 */

import express, { Request, Response, NextFunction } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import compression from 'compression';
import { rateLimitMiddleware, startRateLimitCleanup } from '../middleware/rate-limit';

const app = express();
const port = process.env.PORT || 8080;

// Security middleware
app.use(helmet());
app.use(cors());
app.use(compression());
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));

// Request logging
app.use((req: Request, res: Response, next: NextFunction) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.path}`);
  next();
});

// Health check (no rate limit)
app.get('/health', (req: Request, res: Response) => {
  res.status(200).send('OK');
});

app.get('/api/status', (req: Request, res: Response) => {
  res.json({
    status: 'healthy',
    version: '3.8.0',
    uptime: process.uptime(),
    memory: process.memoryUsage(),
    platform: process.platform,
    node: process.version,
    timestamp: new Date().toISOString()
  });
});

// Root endpoint
app.get('/', (req: Request, res: Response) => {
  res.json({
    name: 'MARIA CODE API',
    version: '3.8.0',
    status: 'running',
    environment: process.env.NODE_ENV || 'development',
    endpoints: {
      health: '/health',
      status: '/api/status',
      image: '/api/v1/image',
      video: '/api/v1/video',
      code: '/api/v1/code',
      chat: '/api/v1/chat'
    },
    timestamp: new Date().toISOString()
  });
});

// ===========================================
// API ENDPOINTS WITH RATE LIMITING
// ===========================================

/**
 * Image Generation Endpoint
 */
app.post('/api/v1/image', rateLimitMiddleware, async (req: Request, res: Response) => {
  try {
    const { prompt, model = 'dall-e-3', size = '1024x1024' } = req.body;
    
    if (!prompt) {
      return res.status(400).json({
        error: 'bad_request',
        message: 'Prompt is required'
      });
    }
    
    // TODO: Implement actual image generation logic
    // For now, return mock response
    return res.json({
      success: true,
      data: {
        url: `https://placeholder.com/generated-image-${Date.now()}.png`,
        prompt,
        model,
        size,
        createdAt: new Date().toISOString()
      }
    });
  } catch (error) {
    console.error('[Image API] Error:', error);
    return res.status(500).json({
      error: 'internal_error',
      message: 'Failed to generate image'
    });
  }
});

/**
 * Video Generation Endpoint
 */
app.post('/api/v1/video', rateLimitMiddleware, async (req: Request, res: Response) => {
  try {
    const { prompt, duration = 5, model = 'runway-gen2' } = req.body;
    
    if (!prompt) {
      return res.status(400).json({
        error: 'bad_request',
        message: 'Prompt is required'
      });
    }
    
    // TODO: Implement actual video generation logic
    return res.json({
      success: true,
      data: {
        url: `https://placeholder.com/generated-video-${Date.now()}.mp4`,
        prompt,
        duration,
        model,
        createdAt: new Date().toISOString()
      }
    });
  } catch (error) {
    console.error('[Video API] Error:', error);
    return res.status(500).json({
      error: 'internal_error',
      message: 'Failed to generate video'
    });
  }
});

/**
 * Code Generation Endpoint
 */
app.post('/api/v1/code', rateLimitMiddleware, async (req: Request, res: Response) => {
  try {
    const { prompt, language = 'typescript', model = 'gpt-4' } = req.body;
    
    if (!prompt) {
      return res.status(400).json({
        error: 'bad_request',
        message: 'Prompt is required'
      });
    }
    
    // TODO: Implement actual code generation logic
    return res.json({
      success: true,
      data: {
        code: `// Generated code for: ${prompt}\nfunction example() {\n  return "Generated by MARIA CODE";\n}`,
        language,
        model,
        prompt,
        createdAt: new Date().toISOString()
      }
    });
  } catch (error) {
    console.error('[Code API] Error:', error);
    return res.status(500).json({
      error: 'internal_error',
      message: 'Failed to generate code'
    });
  }
});

/**
 * Chat Endpoint
 */
app.post('/api/v1/chat', rateLimitMiddleware, async (req: Request, res: Response) => {
  try {
    const { message, model = 'gpt-4' } = req.body;
    
    if (!message) {
      return res.status(400).json({
        error: 'bad_request',
        message: 'Message is required'
      });
    }
    
    // TODO: Implement actual chat logic
    return res.json({
      success: true,
      data: {
        response: `Echo: ${message}`,
        model,
        createdAt: new Date().toISOString()
      }
    });
  } catch (error) {
    console.error('[Chat API] Error:', error);
    return res.status(500).json({
      error: 'internal_error',
      message: 'Failed to process chat'
    });
  }
});

// 404 handler
app.use((req: Request, res: Response) => {
  res.status(404).json({
    error: 'not_found',
    message: 'The requested endpoint does not exist',
    path: req.path
  });
});

// Error handler
app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
  console.error('[Server Error]:', err);
  res.status(500).json({
    error: 'internal_server_error',
    message: 'An unexpected error occurred'
  });
});

// Start server
const server = app.listen(port, () => {
  console.log(`🚀 MARIA CODE Express Server running on port ${port}`);
  console.log(`📍 Health check: http://localhost:${port}/health`);
  console.log(`📍 API Status: http://localhost:${port}/api/status`);
  console.log(`📍 API Endpoints: http://localhost:${port}/`);
  
  // Start rate limit cleanup job
  startRateLimitCleanup();
  console.log('🔧 Rate limit cleanup job started');
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('SIGTERM signal received: closing HTTP server');
  server.close(() => {
    console.log('HTTP server closed');
    process.exit(0);
  });
});

process.on('SIGINT', () => {
  console.log('SIGINT signal received: closing HTTP server');
  server.close(() => {
    console.log('HTTP server closed');
    process.exit(0);
  });
});

export { app, server };