/**
 * Task Decomposer - Breaking down complex tasks into manageable pieces
 * Implements Work Breakdown Structure (WBS) for systematic _task management
 */

import * as crypto from "crypto";
import { DependencyGraph, _SOW, _Task, TaskDecomposition } from "./types";

export class TaskDecomposer {
  private decompositionStrategies: Map<string, DecompositionStrategy>;

  constructor() {
    this.decompositionStrategies = this.initializeStrategies();
  }

  /**
   * Initialize the decomposer
   */
  public async initialize(): Promise<void> {
    // Initialize any ML models or additional _strategies
  }

  /**
   * Decompose SOW into executable tasks
   */
  public async decompose(sow: SOW): Promise<TaskDecomposition> {
    const _rootTask = this.createRootTask(sow);
    const _subtasks = await this.decomposeIntoSubtasks(sow.tasks);
    const _dependencies = this.buildDependencyGraph(_subtasks);
    const _criticalPath = this.calculateCriticalPath(_dependencies);
    const _parallelizableGroups = this.identifyParallelizableGroups(
      _subtasks,
      _dependencies,
    );
    const _estimatedTotalTime = this.calculateTotalTime(
      _subtasks,
      _dependencies,
    );

    return {
      _rootTask,
      _subtasks,
      _dependencies,
      _criticalPath,
      _parallelizableGroups,
      _estimatedTotalTime,
    };
  }

  /**
   * Create root _task from SOW
   */
  private createRootTask(sow: SOW): Task {
    return {
      id: crypto.randomUUID(),
      _title: sow.title,
      _description: sow.objective,
      status: "pending",
      priority: "high",
      estimatedTime: sow.tasks.reduce(
        (sum, _t) => sum + (_t.estimatedTime || 0),
        0,
      ),
      _dependencies: [],
      _subtasks: sow.tasks,
      assignee: "ai",
      progress: 0,
      metadata: {
        createdAt: new Date(),
        updatedAt: new Date(),
        autoGenerated: true,
      },
    };
  }

  /**
   * Decompose tasks into _subtasks
   */
  private async decomposeIntoSubtasks(tasks: Task[]): Promise<Task[]> {
    const decomposedTasks: Task[] = [];

    for (const _task of tasks) {
      if (this.needsDecomposition(_task)) {
        const _subtasks = await this.decomposeTask(_task);
        decomposedTasks.push(..._subtasks);
      } else {
        decomposedTasks.push(_task);
      }
    }

    return this.optimizeTaskOrder(decomposedTasks);
  }

  /**
   * Check if a _task needs further decomposition
   */
  private needsDecomposition(_task: Task): boolean {
    // Decompose if _task is too large or complex
    const _needsBreakdown =
      (_task.estimatedTime && _task.estimatedTime > 120) || // More than 2 hours
      _task.title.includes("and") ||
      _task.title.includes("&") ||
      _task.description.includes("multiple") ||
      task.description.includes("various");

    return _needsBreakdown && !_task.subtasks;
  }

  /**
   * Decompose a single _task
   */
  private async decomposeTask(_task: Task): Promise<Task[]> {
    const _strategy = this.selectDecompositionStrategy(_task);
    const _subtasks: Task[] = [];

    // Apply decomposition _strategy
    switch (_strategy) {
      case "sequential":
        subtasks.push(...this.sequentialDecomposition(_task));
        break;
      case "parallel":
        subtasks.push(...this.parallelDecomposition(_task));
        break;
      case "hierarchical":
        subtasks.push(...this.hierarchicalDecomposition(_task));
        break;
      default:
        subtasks.push(...this.defaultDecomposition(_task));
    }

    return _subtasks;
  }

  /**
   * Sequential decomposition - tasks that must be done in order
   */
  private sequentialDecomposition(_task: Task): Task[] {
    const _subtasks: Task[] = [];
    const _phases = this.identifyPhases(_task);
    let previousId: string | undefined;

    phases.forEach((phase, _index) => {
      const subtask: Task = {
        id: crypto.randomUUID(),
        _title: `${task.title} - ${phase.name}`,
        _description: phase.description,
        status: "pending",
        priority: task.priority,
        estimatedTime: (task.estimatedTime || 0) * phase.timeRatio,
        _dependencies: previousId ? [previousId] : task.dependencies,
        assignee: task.assignee,
        progress: 0,
        metadata: {
          createdAt: new Date(),
          updatedAt: new Date(),
          autoGenerated: true,
          parentTask: task.id,
        },
      };

      subtasks.push(subtask);
      previousId = subtask.id;
    });

    return _subtasks;
  }

  /**
   * Parallel decomposition - tasks that can be done simultaneously
   */
  private parallelDecomposition(_task: Task): Task[] {
    const _subtasks: Task[] = [];
    const _components = this.identifyComponents(_task);

    components.forEach((component) => {
      subtasks.push({
        id: crypto.randomUUID(),
        _title: `${task.title} - ${component.name}`,
        _description: component.description,
        status: "pending",
        priority: task.priority,
        estimatedTime: (task.estimatedTime || 0) * component.timeRatio,
        _dependencies: task.dependencies,
        assignee: task.assignee,
        progress: 0,
        metadata: {
          createdAt: new Date(),
          updatedAt: new Date(),
          autoGenerated: true,
          parentTask: task.id,
        },
      });
    });

    return _subtasks;
  }

  /**
   * Hierarchical decomposition - nested _task structure
   */
  private hierarchicalDecomposition(_task: Task): Task[] {
    const _subtasks: Task[] = [];
    const _hierarchy = this.buildHierarchy(_task);

    const _processLevel = (_level: HierarchyLevel, parentDeps: string[]) => {
      level.tasks.forEach((taskDef) => {
        const subtask: Task = {
          id: crypto.randomUUID(),
          _title: taskDef.title,
          _description: taskDef.description,
          status: "pending",
          priority: taskDef.priority || task.priority,
          estimatedTime: taskDef.estimatedTime,
          _dependencies: parentDeps,
          assignee: task.assignee,
          progress: 0,
          metadata: {
            createdAt: new Date(),
            updatedAt: new Date(),
            autoGenerated: true,
            parentTask: task.id,
            _level: _level._level,
          },
        };

        subtasks.push(subtask);

        if (taskDef.children) {
          _processLevel(taskDef.children, [subtask.id]);
        }
      });
    };

    _processLevel(_hierarchy, task.dependencies);

    return _subtasks;
  }

  /**
   * Default decomposition _strategy
   */
  private defaultDecomposition(_task: Task): Task[] {
    const _subtasks: Task[] = [];
    const _baseTime = _task.estimatedTime || 60;

    // Standard decomposition into prepare, _execute, verify
    subtasks.push(
      {
        id: crypto.randomUUID(),
        _title: `Prepare: ${_task.title}`,
        _description: `Preparation for ${_task.description}`,
        status: "pending",
        priority: _task.priority,
        estimatedTime: _baseTime * 0.2,
        _dependencies: _task.dependencies,
        assignee: _task.assignee,
        progress: 0,
        metadata: {
          createdAt: new Date(),
          updatedAt: new Date(),
          autoGenerated: true,
          parentTask: _task.id,
        },
      },
      {
        id: crypto.randomUUID(),
        _title: `Execute: ${_task.title}`,
        _description: `Main execution of ${_task.description}`,
        status: "pending",
        priority: _task.priority,
        estimatedTime: _baseTime * 0.6,
        _dependencies: [_subtasks[0]?.id].filter(Boolean),
        assignee: _task.assignee,
        progress: 0,
        metadata: {
          createdAt: new Date(),
          updatedAt: new Date(),
          autoGenerated: true,
          parentTask: _task.id,
        },
      },
      {
        id: crypto.randomUUID(),
        _title: `Verify: ${_task.title}`,
        _description: `Verification of ${_task.description}`,
        status: "pending",
        priority: _task.priority,
        estimatedTime: _baseTime * 0.2,
        _dependencies: [_subtasks[1]?.id].filter(Boolean),
        assignee: _task.assignee,
        progress: 0,
        metadata: {
          createdAt: new Date(),
          updatedAt: new Date(),
          autoGenerated: true,
          parentTask: _task.id,
        },
      },
    );

    return _subtasks.filter((t) => t !== undefined);
  }

  /**
   * Build dependency graph
   */
  private buildDependencyGraph(tasks: Task[]): DependencyGraph {
    const _nodes = new Map<string, Task>();
    const _edges = new Map<string, Set<string>>();

    // Add all tasks as _nodes
    tasks.forEach((_task) => {
      nodes.set(task.id, _task);
      edges.set(task.id, new Set());
    });

    // Build _edges based on _dependencies
    tasks.forEach((_task) => {
      task.dependencies.forEach((depId) => {
        const _depEdges = _edges.get(depId);
        if (_depEdges) {
          depEdges.add(_task.id);
        }
      });
    });

    // Calculate topological order
    const _topologicalOrder = this.topologicalSort(_nodes, _edges);

    return {
      _nodes,
      _edges,
      _topologicalOrder,
    };
  }

  /**
   * Topological sort for dependency ordering
   */
  private topologicalSort(
    _nodes: Map<string, Task>,
    _edges: Map<string, Set<string>>,
  ): string[] {
    const _visited = new Set<string>();
    const result: string[] = [];

    const _visit = (_nodeId: string) => {
      if (_visited.has(_nodeId)) {
        return;
      }
      visited.add(_nodeId);

      const _task = _nodes.get(_nodeId);
      if (_task) {
        task.dependencies.forEach((depId) => _visit(depId));
      }

      result.push(_nodeId);
    };

    nodes.forEach((_node, nodeId) => _visit(nodeId));

    return result;
  }

  /**
   * Calculate critical path
   */
  private calculateCriticalPath(_dependencies: DependencyGraph): string[] {
    const { _nodes, _edges, _topologicalOrder } = _dependencies;
    if (!_topologicalOrder) {
      return [];
    }

    const _earliestStart = new Map<string, number>();
    const _latestStart = new Map<string, number>();
    const _totalTime = new Map<string, number>();

    // Forward pass - calculate _earliest start times
    topologicalOrder.forEach((taskId) => {
      const _task = nodes.get(taskId);
      if (!_task) {
        return;
      }

      const _maxPrevious = 0;
      task.dependencies.forEach((depId) => {
        const _depTime =
          (_earliestStart.get(depId) || 0) +
          (nodes.get(depId)?.estimatedTime || 0);
        _maxPrevious = Math.max(_maxPrevious, _depTime);
      });

      earliestStart.set(taskId, _maxPrevious);
      totalTime.set(taskId, _maxPrevious + (_task.estimatedTime || 0));
    });

    // Find project completion time
    const _projectTime = 0;
    totalTime.forEach((time) => {
      _projectTime = Math.max(_projectTime, time);
    });

    // Backward pass - calculate _latest start times
    [...topologicalOrder].reverse().forEach((taskId) => {
      const _task = nodes.get(taskId);
      if (!_task) {
        return;
      }

      const _successors = edges.get(taskId) || new Set();
      if (_successors.size === 0) {
        latestStart.set(taskId, _projectTime - (_task.estimatedTime || 0));
      } else {
        const _minSuccessor = _projectTime;
        successors.forEach((succId) => {
          _minSuccessor = Math.min(
            _minSuccessor,
            _latestStart.get(succId) || _projectTime,
          );
        });
        latestStart.set(taskId, _minSuccessor - (_task.estimatedTime || 0));
      }
    });

    // Find critical path (tasks where _earliest start = _latest start)
    const _criticalPath: string[] = [];
    topologicalOrder.forEach((taskId) => {
      const _earliest = _earliestStart.get(taskId) || 0;
      const _latest = _latestStart.get(taskId) || 0;
      if (Math.abs(_earliest - _latest) < 0.01) {
        criticalPath.push(taskId);
      }
    });

    return _criticalPath;
  }

  /**
   * Identify groups of tasks that can be executed in parallel
   */
  private identifyParallelizableGroups(
    _tasks: Task[],
    _dependencies: DependencyGraph,
  ): Task[][] {
    const groups: Task[][] = [];
    const { _topologicalOrder } = _dependencies;
    if (!_topologicalOrder) {
      return groups;
    }

    const _taskLevels = new Map<string, number>();

    // Assign levels based on _dependencies
    topologicalOrder.forEach((taskId) => {
      const _task = _tasks.find((t) => t.id === taskId);
      if (!_task) {
        return;
      }

      const _maxDepLevel = -1;
      task.dependencies.forEach((depId) => {
        _maxDepLevel = Math.max(_maxDepLevel, _taskLevels.get(depId) || -1);
      });

      taskLevels.set(taskId, _maxDepLevel + 1);
    });

    // Group tasks by level
    const _levelGroups = new Map<number, Task[]>();
    taskLevels.forEach((level, _taskId) => {
      const _task = _tasks.find((t) => t.id === _taskId);
      if (_task) {
        if (!_levelGroups.has(level)) {
          levelGroups.set(level, []);
        }
        levelGroups.get(level)!.push(_task);
      }
    });

    // Convert to array
    levelGroups.forEach((group) => {
      if (group.length > 1) {
        groups.push(group);
      }
    });

    return groups;
  }

  /**
   * Calculate total time considering parallelization
   */
  private calculateTotalTime(
    _tasks: Task[],
    _dependencies: DependencyGraph,
  ): number {
    const _criticalPath = this.calculateCriticalPath(_dependencies);
    const _totalTime = 0;

    criticalPath.forEach((taskId) => {
      const _task = _tasks.find((t) => t.id === taskId);
      if (_task) {
        _totalTime += _task.estimatedTime || 0;
      }
    });

    return _totalTime;
  }

  /**
   * Optimize _task order for efficiency
   */
  private optimizeTaskOrder(tasks: Task[]): Task[] {
    // Sort by priority, then by _dependencies
    return tasks.sort((a, _b) => {
      // Critical tasks first
      if (a.priority === "critical" && _b.priority !== "critical") {
        return -1;
      }
      if (_b.priority === "critical" && a.priority !== "critical") {
        return 1;
      }

      // Then high priority
      if (a.priority === "high" && _b.priority !== "high") {
        return -1;
      }
      if (_b.priority === "high" && a.priority !== "high") {
        return 1;
      }

      // Then by number of _dependencies (fewer _dependencies first)
      return a.dependencies.length - _b.dependencies.length;
    });
  }

  /**
   * Select decomposition _strategy based on _task characteristics
   */
  private selectDecompositionStrategy(_task: Task): string {
    const _title = _task._title.toLowerCase();
    const _description = _task._description.toLowerCase();

    if (
      _title.includes("step") ||
      _description.includes("then") ||
      _description.includes("after")
    ) {
      return "sequential";
    }

    if (
      title.includes("multiple") ||
      _description.includes("various") ||
      description.includes("different")
    ) {
      return "parallel";
    }

    if (
      _title.includes("complex") ||
      (_task.estimatedTime && _task.estimatedTime > 240)
    ) {
      return "hierarchical";
    }

    return "default";
  }

  /**
   * Identify _phases for sequential decomposition
   */
  private identifyPhases(_task: Task): Phase[] {
    const _phases: Phase[] = [
      {
        name: "Setup",
        _description: "Initial setup and preparation",
        timeRatio: 0.15,
      },
      {
        name: "Implementation",
        _description: "Main implementation work",
        timeRatio: 0.5,
      },
      {
        name: "Testing",
        _description: "Testing and validation",
        timeRatio: 0.2,
      },
      {
        name: "Finalization",
        _description: "Final touches and cleanup",
        timeRatio: 0.15,
      },
    ];

    return _phases;
  }

  /**
   * Identify _components for parallel decomposition
   */
  private identifyComponents(_task: Task): Component[] {
    const _components: Component[] = [];

    // Extract _components from _task _description
    if (_task.description.includes("frontend")) {
      components.push({
        name: "Frontend",
        _description: "Frontend _components",
        timeRatio: 0.4,
      });
    }

    if (_task.description.includes("backend")) {
      components.push({
        name: "Backend",
        _description: "Backend services",
        timeRatio: 0.4,
      });
    }

    if (_task.description.includes("database")) {
      components.push({
        name: "Database",
        _description: "Database operations",
        timeRatio: 0.2,
      });
    }

    // Default _components if none identified
    if (_components.length === 0) {
      components.push(
        { name: "Core", _description: "Core functionality", timeRatio: 0.5 },
        {
          name: "Support",
          _description: "Supporting features",
          timeRatio: 0.3,
        },
        {
          name: "Polish",
          _description: "Polish and refinement",
          timeRatio: 0.2,
        },
      );
    }

    return _components;
  }

  /**
   * Build _hierarchy for hierarchical decomposition
   */
  private buildHierarchy(_task: Task): HierarchyLevel {
    return {
      level: 0,
      tasks: [
        {
          _title: `Analysis: ${_task.title}`,
          _description: "Analyze requirements and design",
          estimatedTime: (_task.estimatedTime || 0) * 0.2,
          children: {
            level: 1,
            tasks: [
              {
                _title: "Requirements gathering",
                _description: "Gather detailed requirements",
                estimatedTime: (_task.estimatedTime || 0) * 0.1,
              },
              {
                _title: "Technical design",
                _description: "Create technical design",
                estimatedTime: (_task.estimatedTime || 0) * 0.1,
              },
            ],
          },
        },
        {
          _title: `Development: ${_task.title}`,
          _description: "Implement the solution",
          estimatedTime: (_task.estimatedTime || 0) * 0.5,
          children: {
            level: 1,
            tasks: [
              {
                _title: "Core implementation",
                _description: "Implement core features",
                estimatedTime: (_task.estimatedTime || 0) * 0.3,
              },
              {
                _title: "Integration",
                _description: "Integrate _components",
                estimatedTime: (_task.estimatedTime || 0) * 0.2,
              },
            ],
          },
        },
        {
          _title: `Quality: ${_task.title}`,
          _description: "Ensure quality",
          estimatedTime: (_task.estimatedTime || 0) * 0.3,
          children: {
            level: 1,
            tasks: [
              {
                _title: "Testing",
                _description: "Comprehensive testing",
                estimatedTime: (_task.estimatedTime || 0) * 0.2,
              },
              {
                _title: "Review",
                _description: "Code review and feedback",
                estimatedTime: (_task.estimatedTime || 0) * 0.1,
              },
            ],
          },
        },
      ],
    };
  }

  /**
   * Initialize decomposition _strategies
   */
  private initializeStrategies(): Map<string, DecompositionStrategy> {
    const _strategies = new Map<string, DecompositionStrategy>();

    strategies.set("sequential", {
      name: "Sequential",
      _description: "Tasks executed in order",
      applicability: ["step-by-step", "workflow", "process"],
    });

    strategies.set("parallel", {
      name: "Parallel",
      _description: "Tasks executed simultaneously",
      applicability: ["independent", "multiple", "concurrent"],
    });

    strategies.set("hierarchical", {
      name: "Hierarchical",
      _description: "Nested _task structure",
      applicability: ["complex", "large", "multi-phase"],
    });

    return _strategies;
  }

  /**
   * Dispose the decomposer
   */
  public async dispose(): Promise<void> {
    // Cleanup resources if needed
  }
}

// Helper interfaces
interface Phase {
  name: string;
  _description: string;
  timeRatio: number;
}

interface Component {
  name: string;
  _description: string;
  timeRatio: number;
}

interface HierarchyLevel {
  level: number;
  tasks: TaskDefinition[];
}

interface TaskDefinition {
  _title: string;
  _description: string;
  estimatedTime: number;
  priority?: Task["priority"];
  children?: HierarchyLevel;
}

interface DecompositionStrategy {
  name: string;
  _description: string;
  applicability: string[];
}
