/**
 * Template Provider - Always available fallback provider
 */

import { AIProvider, GenerateOptions, GenerateResult } from "./types";
import { TemplateRepo } from "../templates/TemplateRepo";

export class TemplateProvider implements AIProvider {
  id = "template:static";
  modelId = "template";
  vendor = "template" as const;
  name = "Template Fallback Provider";

  constructor(private repo: TemplateRepo) {}

  available(): boolean {
    return true; // Always available
  }

  async generate(
    prompt: string,
    opts?: GenerateOptions,
  ): Promise<GenerateResult> {
    const lower = prompt.toLowerCase();

    // Detect what user wants and return appropriate template
    let templateKey = "hello-html";
    let code: string;

    if (/tetris|テトリス|game|ゲーム/.test(lower) && /html|index/.test(lower)) {
      templateKey = "basic-html-index";
    } else if (/error/.test(lower) && /html|page/.test(lower)) {
      templateKey = "error-page";
    } else if (/typescript|\.ts/.test(lower)) {
      templateKey = "basic-typescript";
    } else if (/javascript|\.js/.test(lower)) {
      templateKey = "basic-javascript";
    } else if (/html|index|web/.test(lower)) {
      templateKey = "hello-html";
    }

    try {
      code = await this.repo.get(templateKey);
    } catch {
      // Fallback to a minimal template
      code = `<!doctype html>
<html>
<head><title>Generated</title></head>
<body>
  <h1>Generated by MARIA</h1>
  <p>Request: ${prompt.substring(0, 100)}</p>
</body>
</html>`;
    }

    return {
      code,
      finishReason: "stop",
      modelId: this.modelId,
      providerId: this.id,
    };
  }
}
