# Branch Protection Rules for main branch
# Apply these settings in GitHub repository settings

protection_rules:
  main:
    # Require pull request reviews before merging
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 2
      require_last_push_approval: true
      
    # Require status checks to pass before merging
    required_status_checks:
      strict: true  # Require branches to be up to date before merging
      contexts:
        - "build"
        - "test"
        - "lint"
        - "typecheck"
        - "security-scan"
        
    # Enforce restrictions
    restrictions:
      users: ["bonginkan"]
      teams: ["maintainers"]
      apps: []
      
    # Enforce admins
    enforce_admins: true
    
    # Require signed commits
    required_signatures: true
    
    # Require conversation resolution before merging
    required_conversation_resolution: true
    
    # Require linear history
    required_linear_history: true
    
    # Allow force pushes
    allow_force_pushes: false
    
    # Allow deletions
    allow_deletions: false
    
    # Block force pushes
    block_creations: false
    
    # Lock branch
    lock_branch: false

  develop:
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 1
      
    required_status_checks:
      strict: true
      contexts:
        - "build"
        - "test"
        - "lint"
        
    allow_force_pushes: false
    allow_deletions: false