import { BaseService } from "../../internal-mode/core/BaseService";
import fs from "node:fs/promises";
import path from "node:path";

export interface WebSOWOptions {
  profile: string;
  a11y: boolean;
  perf: boolean;
  out?: string;
}

export class WebSOWService extends BaseService {
  id = "web-sowservice";
  version = "1.0.0";

  async generate(options: WebSOWOptions): Promise<string> {
    const outputPath = options.out || "docs/WEB_SOW.md";

    const sow = this.generateSOWContent(options);

    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, sow);

    return outputPath;
  }

  private generateSOWContent(options: WebSOWOptions): string {
    const profile = options.profile || "landing";
    const date = new Date().toLocaleDateString("ja-JP");

    return `# SOW — Web ${profile.toUpperCase()} (Auto-Generated)

**Generated:** ${date}  
**Profile:** ${profile}  
**A11y:** ${options.a11y ? "✅ Enabled" : "❌ Disabled"}  
**Performance:** ${options.perf ? "✅ Enabled" : "❌ Disabled"}

## 🎯 目的・KPI
- **主要KPI**: CVR 4% → 5% (目標設定)
- **パフォーマンス**: ${options.perf ? "LCP ≤ 2.5s, CLS < 0.1, FID ≤ 100ms" : "標準設定"}
- **アクセシビリティ**: ${options.a11y ? "WCAG 2.1 AA準拠, ALT属性100%" : "基本対応"}
- **SEO**: メタタグ最適化, 構造化データ対応

## 📋 スコープ
### Pages (${profile} profile)
${this.getPagesByProfile(profile)}

### コンポーネント
- **Header**: ロゴ/ナビゲーション/CTA
- **Hero**: メイン見出し/サブコピー/ビジュアル/主要CTA  
- **Features**: 機能紹介グリッド/アイコン/説明
- **Social Proof**: お客様の声/導入事例/ロゴ
- **CTA Sections**: 複数箇所での行動喚起
- **Footer**: 会社情報/リンク/コンタクト

## 📅 スケジュール
- **W1**: ブリーフィング/要件定義/ワイヤーフレーム
- **W2**: ビジュアルデザイン/アセット制作  
- **W3**: 実装/コンテンツ統合
- **W4**: QA/パフォーマンス最適化/リリース

## 👥 体制・責任
- **PM**: @pm (プロジェクト管理/承認/調整)
- **Design**: @designer (UI/UX設計/ビジュアル制作)
- **Copy**: @copywriter (コンテンツ制作/文言調整)
- **Dev**: @developer (実装/統合/最適化)
- **QA**: @qa (品質保証/テスト)

## ⚖️ ガバナンス・承認フロー
### 品質基準
${this.getQualityGates(options)}

### 承認プロセス
- **デザイン承認**: PM + Brand Manager (2者承認)
- **コンテンツ承認**: PM + Legal (必要に応じて)
- **最終承認**: PM + Stakeholder

### 納品規格
- **画像**: WebP/AVIF優先, PNG/JPG fallback
- **動画**: MP4 H.264 1080p, 適切な圧縮率
- **ソースファイル**: 編集可能な形式で提供

## ⚠️ リスク・制約
### 高リスク項目
- **権利・素材**: 外部素材利用禁止 → 自社生成/社内素材のみ使用
- **ブランド逸脱**: ガイドライン遵守 → デザインレビュー必須  
- **パフォーマンス劣化**: ${options.perf ? "Core Web Vitals監視 → 継続的最適化" : "基本的なパフォーマンス確認"}

### 緩和策
- 事前ブランドキット生成 (/design brand)
- 段階的承認プロセス
- ${options.a11y ? "アクセシビリティ自動テスト導入" : "基本的なアクセシビリティチェック"}

## 🔄 運用・保守
- **更新頻度**: 月次コンテンツ更新
- **A/Bテスト**: CTA/ヘッドライン最適化
- **分析・改善**: Google Analytics/ヒートマップ分析

## 📊 成功メトリクス
- CVR: 現行 → 目標5%以上  
- セッション時間: 2分以上
- 離脱率: 60%以下
- ${options.perf ? "Core Web Vitals: Good評価" : "ページ読み込み時間: 3秒以内"}
- ${options.a11y ? "アクセシビリティスコア: 95%以上" : "Lighthouse Performance: 80%以上"}

---
*Generated by MARIA Design System*
`;
  }

  private getPagesByProfile(profile: string): string {
    switch (profile) {
      case "landing":
        return `- **Home**: メインランディングページ
- **Features**: 機能詳細
- **Pricing**: 料金プラン  
- **Contact**: お問い合わせ`;

      case "site":
        return `- **Home**: トップページ
- **About**: 会社概要
- **Services**: サービス一覧
- **Portfolio**: 実績・事例
- **Blog**: ブログ/お知らせ
- **Contact**: お問い合わせ`;

      default:
        return `- **Home**: メインページ
- **Features**: 機能・特徴
- **Contact**: お問い合わせ`;
    }
  }

  private getQualityGates(options: WebSOWOptions): string {
    const gates: string[] = [];

    if (options.perf) {
      gates.push("- **Performance**: LCP ≤ 2.5s, CLS < 0.1, FID ≤ 100ms");
      gates.push("- **Lighthouse**: Performance Score 90+");
    } else {
      gates.push("- **Performance**: 基本的な読み込み速度確認");
    }

    if (options.a11y) {
      gates.push("- **Accessibility**: WCAG 2.1 AA準拠");
      gates.push("- **ALT属性**: 画像100%対応");
      gates.push("- **色コントラスト**: AA基準クリア");
    } else {
      gates.push("- **Accessibility**: 基本的なアクセシビリティ対応");
    }

    gates.push("- **SEO**: メタタグ/構造化データ実装");
    gates.push("- **ブランド**: デザインガイドライン準拠");
    gates.push("- **Legal**: 権利クリアランス確認");

    return gates.join("\n");
  }
}
