import chalk from "chalk";

export class DiagramHandler {
  async execute(args: string[]): Promise<string> {
    const _input = args.join(" ").trim();

    if (!_input || _input === "--help") {
      return this.showHelp();
    }

    // Parse diagram type from _input
    if (_input.startsWith("_flowchart")) {
      return this.generateFlowchart(_input.replace("_flowchart", "").trim());
    } else if (_input.startsWith("_architecture")) {
      return this.generateArchitecture(
        _input.replace("_architecture", "").trim(),
      );
    } else if (_input.startsWith("er") || _input.startsWith("entity")) {
      return this.generateERDiagram(_input.replace(/^(er|entity)/, "").trim());
    } else if (_input.startsWith("_sequence")) {
      return this.generateSequenceDiagram(
        _input.replace("_sequence", "").trim(),
      );
    } else if (_input.startsWith("class")) {
      return this.generateClassDiagram(_input.replace("class", "").trim());
    } else if (_input.startsWith("mind-map") || _input.startsWith("mindmap")) {
      return this.generateMindMap(
        _input.replace(/^(mind-map|mindmap)/, "").trim(),
      );
    }

    // Auto-detect diagram type
    return this.autoGenerateDiagram(_input);
  }

  private showHelp(): string {
    return `
${chalk.cyan("🎨 Visual Diagram Generation")}

${chalk.yellow("Usage:")}
  /diagram <type> <description>     Generate specific diagram type
  /diagram <description>            Auto-detect diagram type

${chalk.yellow("Diagram Types:")}
  _flowchart <process>              Process flowcharts
  _architecture <system>            System _architecture diagrams
  er <database>                    Entity-relationship diagrams
  _sequence <interaction>           Sequence diagrams
  class <model>                    UML class diagrams
  mind-map <topic>                 Mind map generation

${chalk.yellow("Options:")}
  --style <style>   Design style (modern, classic, minimal)
  --format <fmt>    Output format (ascii, svg, html)
  --color           Use colored output
  --export <file>   Export to file

${chalk.yellow("Examples:")}
  /diagram _flowchart login process
  /diagram _architecture microservices
  /diagram er user database
  /diagram _sequence API request
  /diagram class User model
  /diagram mind-map project planning

${chalk.gray("Creates beautiful ASCII art diagrams for documentation and visualization.")}
    `.trim();
  }

  private generateFlowchart(description: string): string {
    console.log(chalk.cyan("🎨 Generating Flowchart..."));
    console.log(chalk.gray(`📐 Analyzing process: ${description}...`));

    // Generate a sample _flowchart based on common patterns
    const _flowchart = this.createLoginFlowchart(description);

    return `
${chalk.green("✅ Flowchart Generated:")}

${chalk.cyan(`Process: ${description || "Generic Flow"}`)}

${_flowchart}

${chalk.yellow("💡 Features:")}
  • Decision points highlighted
  • Process flow clearly marked
  • Start/End nodes identified
  
${chalk.gray("💾 Use --export to save as file")}
    `.trim();
  }

  private generateArchitecture(description: string): string {
    console.log(chalk.cyan("🎨 Generating Architecture Diagram..."));
    console.log(chalk.gray(`🏗️ Analyzing _architecture: ${description}...`));

    const _architecture = this.createMicroservicesArchitecture(description);

    return `
${chalk.green("✅ Architecture Diagram Created:")}

${chalk.cyan(`System: ${description || "Generic Architecture"}`)}

${_architecture}

${chalk.yellow("📋 Components:")}
  • API Gateway Layer
  • Service Discovery
  • Business Services
  • Data Layer
  • Message Queue

${chalk.gray("💾 Saved as: ./diagrams/architecture.txt")}
    `.trim();
  }

  private generateERDiagram(description: string): string {
    console.log(chalk.cyan("🎨 Generating ER Diagram..."));

    const _erDiagram = this.createUserERDiagram();

    return `
${chalk.green("✅ Entity-Relationship Diagram Created:")}

${chalk.cyan(`Database: ${description || "User Database"}`)}

${_erDiagram}

${chalk.yellow("📋 Entities:")}
  • User (id, name, email, created_at)
  • Profile (id, user_id, bio, avatar)
  • Post (id, user_id, title, content)
  • Comment (id, post_id, user_id, text)

${chalk.yellow("🔗 Relationships:")}
  • User 1:1 Profile
  • User 1:N Posts
  • Post 1:N Comments
  • User 1:N Comments

${chalk.gray("💾 Use --format svg for vector output")}
    `.trim();
  }

  private generateSequenceDiagram(description: string): string {
    const _sequence = this.createAPISequence();

    return `
${chalk.green("✅ Sequence Diagram Created:")}

${chalk.cyan(`Interaction: ${description || "API Request Flow"}`)}

${_sequence}

${chalk.yellow("📋 Participants:")}
  • Client
  • API Gateway
  • Auth Service
  • Business Logic
  • Database

${chalk.gray("💾 Export available in multiple formats")}
    `.trim();
  }

  private generateClassDiagram(description: string): string {
    const _classDiagram = this.createUserClassDiagram();

    return `
${chalk.green("✅ UML Class Diagram Created:")}

${chalk.cyan(`Model: ${description || "User Model"}`)}

${_classDiagram}

${chalk.yellow("📋 Classes:")}
  • User (Abstract)
  • Customer extends User
  • Admin extends User
  • Profile (Composition)

${chalk.gray("💾 Supports PlantUML export")}
    `.trim();
  }

  private generateMindMap(description: string): string {
    const _mindMap = this.createProjectMindMap();

    return `
${chalk.green("✅ Mind Map Created:")}

${chalk.cyan(`Topic: ${description || "Project Planning"}`)}

${_mindMap}

${chalk.yellow("📋 Branches:")}
  • Requirements
  • Design
  • Implementation
  • Testing
  • Deployment

${chalk.gray("💾 Interactive HTML version available")}
    `.trim();
  }

  private autoGenerateDiagram(description: string): string {
    // Auto-detect diagram type based on keywords
    if (description.includes("flow") || description.includes("process")) {
      return this.generateFlowchart(description);
    } else if (
      description.includes("_architecture") ||
      description.includes("system")
    ) {
      return this.generateArchitecture(description);
    } else if (
      description.includes("database") ||
      description.includes("table")
    ) {
      return this.generateERDiagram(description);
    } else if (
      description.includes("_sequence") ||
      description.includes("interaction")
    ) {
      return this.generateSequenceDiagram(description);
    } else if (description.includes("class") || description.includes("model")) {
      return this.generateClassDiagram(description);
    } else {
      return this.generateFlowchart(description);
    }
  }

  // ASCII Art Diagram Generators

  private createLoginFlowchart(_description: string): string {
    return `
    ┌─────────────┐
    │    START    │
    └──────┬──────┘
           │
           ▼
    ┌─────────────┐
    │ Enter Login │
    │    Page     │
    └──────┬──────┘
           │
           ▼
    ┌─────────────┐
    │   Submit    │
    │ Credentials │
    └──────┬──────┘
           │
           ▼
       ◆───────◆
      ╱ Valid?  ╲
     ╱            ╲
    ◆──────────────◆
    │ Yes      No  │
    ▼              ▼
┌─────────┐  ┌──────────┐
│Dashboard│  │Show Error│
└────┬────┘  └────┬─────┘
     │            │
     ▼            │
┌─────────┐       │
│   END   │◄──────┘
└─────────┘`;
  }

  private createMicroservicesArchitecture(_description: string): string {
    return `
┌─────────────────────────────────────────────────────────────┐
│                        Client Layer                         │
│                    (Web, Mobile, Desktop)                   │
└─────────────────────────────┬───────────────────────────────┘
                              │
                              ▼
┌─────────────────────────────────────────────────────────────┐
│                       API Gateway                           │
│                   (Load Balancer, Auth)                     │
└────────┬──────────────┬─────────────┬──────────────┬────────┘
         │              │             │              │
         ▼              ▼             ▼              ▼
    ┌─────────┐    ┌─────────┐  ┌─────────┐   ┌─────────┐
    │  Auth   │    │  User   │  │ Product │   │  Order  │
    │ Service │    │ Service │  │ Service │   │ Service │
    └────┬────┘    └────┬────┘  └────┬────┘   └────┬────┘
         │              │             │              │
         └──────────────┴─────────────┴──────────────┘
                              │
                              ▼
         ┌────────────────────────────────────────────┐
         │            Message Queue (RabbitMQ)        │
         └────────────────────────────────────────────┘
                              │
         ┌────────────────────┴────────────────────┐
         ▼                                          ▼
    ┌──────────┐                           ┌──────────────┐
    │ MongoDB  │                           │  PostgreSQL  │
    └──────────┘                           └──────────────┘`;
  }

  private createUserERDiagram(): string {
    return `
    ┌──────────────┐           ┌──────────────┐
    │     USER     │           │   PROFILE    │
    ├──────────────┤           ├──────────────┤
    │ PK: id       │───────────│ PK: id       │
    │ name         │     1:1   │ FK: user_id  │
    │ email        │           │ bio          │
    │ password     │           │ avatar_url   │
    │ created_at   │           │ updated_at   │
    └──────┬───────┘           └──────────────┘
           │
           │ 1:N
           │
    ┌──────▼───────┐           ┌──────────────┐
    │     POST     │           │   COMMENT    │
    ├──────────────┤           ├──────────────┤
    │ PK: id       │───────────│ PK: id       │
    │ FK: user_id  │     1:N   │ FK: post_id  │
    │ title        │           │ FK: user_id  │
    │ content      │           │ text         │
    │ published_at │           │ created_at   │
    └──────────────┘           └──────────────┘`;
  }

  private createAPISequence(): string {
    return `
Client        Gateway       Auth         Service      Database
  │              │            │             │            │
  │   Request    │            │             │            │
  │─────────────>│            │             │            │
  │              │  Validate  │             │            │
  │              │───────────>│             │            │
  │              │            │             │            │
  │              │<───────────│             │            │
  │              │   Token    │             │            │
  │              │            │             │            │
  │              │      Process Request     │            │
  │              │─────────────────────────>│            │
  │              │            │             │   Query    │
  │              │            │             │───────────>│
  │              │            │             │            │
  │              │            │             │<───────────│
  │              │            │             │   Result   │
  │              │<─────────────────────────│            │
  │   Response   │            │             │            │
  │<─────────────│            │             │            │
  │              │            │             │            │`;
  }

  private createUserClassDiagram(): string {
    return `
    ┌─────────────────────────────┐
    │      <<abstract>>           │
    │          User               │
    ├─────────────────────────────┤
    │ - id: string                │
    │ - name: string              │
    │ - email: string             │
    │ # createdAt: Date           │
    ├─────────────────────────────┤
    │ + getName(): string         │
    │ + getEmail(): string        │
    │ + authenticate(): boolean   │
    └──────────┬──────────────────┘
               │
       ┌───────┴────────┐
       │                │
┌──────▼─────┐   ┌──────▼──────┐
│  Customer  │   │    Admin    │
├────────────┤   ├─────────────┤
│ - tier     │   │ - role      │
│ - credits  │   │ - dept      │
├────────────┤   ├─────────────┤
│ + buy()    │   │ + ban()     │
│ + refund() │   │ + promote() │
└────────────┘   └─────────────┘`;
  }

  private createProjectMindMap(): string {
    return `
                            Project Planning
                                   │
                ┌──────────────────┼──────────────────┐
                │                  │                  │
          Requirements          Design          Implementation
                │                  │                  │
        ┌───────┼───────┐   ┌─────┼─────┐   ┌───────┼───────┐
        │       │       │   │     │     │   │       │       │
     User    Tech    Time  UI   API   DB  Frontend Backend Tests
     Story   Stack   Est.  Mock Schema     React   Node.js Jest
        │       │       │
    ┌───┼───┐   │   ┌───┼───┐
    │   │   │   │   │   │   │
  Auth Shop Cart│ 2wk 4wk 1wk
               Next  
               AWS`;
  }
}
