/**
 * Low-Risk Recipes
 * Safe, automatic healing recipes for common issues
 */

import { FixRecipe } from "../types";

export const LOW_RISK_RECIPES: FixRecipe[] = [
  {
    id: "env-setup",
    name: ".env.local生成",
    description: "環境設定ファイルのテンプレート作成",
    match: {
      issueType: "CONFIG_MISSING",
      conditions: {
        file: ".env.local",
      },
    },
    risk: {
      impact: "low",
      probability: "rare",
      score: 0.1,
    },
    requiresApproval: false,
    timeout: 5000,
    actions: {
      dryRun: [
        {
          type: "file:check",
          args: { path: ".env.local" },
        },
      ],
      apply: [
        {
          type: "file:backup",
          args: { path: ".env.local" },
        },
        {
          type: "file:ensure",
          args: { path: ".env.local" },
        },
        {
          type: "file:appendUnique",
          args: {
            path: ".env.local",
            lines: [
              "# MARIA Environment Configuration",
              "# Generated by Self-Healing Doctor System",
              "",
              "# AI Provider API Keys",
              "OPENAI_API_KEY=",
              "ANTHROPIC_API_KEY=",
              "GOOGLE_API_KEY=",
              "",
              "# Local AI Providers",
              "LMSTUDIO_API_URL=http://localhost:1234",
              "OLLAMA_API_URL=http://localhost:11434",
              "VLLM_API_URL=http://localhost:8000",
              "",
              "# Development Settings",
              "DEBUG=false",
              "LOG_LEVEL=info",
            ],
          },
        },
      ],
      verify: [
        {
          type: "file:exists",
          args: { path: ".env.local" },
        },
      ],
      rollback: [
        {
          type: "file:restore",
          args: {
            path: ".env.local",
            backupPath: ".env.local.bak",
          },
        },
      ],
    },
  },

  {
    id: "cache-clear",
    name: "キャッシュクリア",
    description: "破損したキャッシュの削除と再生成",
    match: {
      issueType: "CACHE_CORRUPT",
    },
    risk: {
      impact: "low",
      probability: "possible",
      score: 0.1,
    },
    requiresApproval: false,
    timeout: 10000,
    actions: {
      dryRun: [
        {
          type: "cache:check",
          args: {
            paths: ["~/.maria/cache", ".turbo", ".cache/maria"],
          },
        },
      ],
      apply: [
        {
          type: "cache:purge",
          args: {
            paths: ["~/.maria/cache"],
          },
        },
        {
          type: "cache:purge",
          args: {
            paths: [".turbo"],
          },
        },
        {
          type: "cache:purge",
          args: {
            paths: [".cache/maria"],
          },
        },
        {
          type: "cache:warmup",
          args: {
            targets: ["models:list", "aliases", "templates"],
          },
        },
      ],
      verify: [
        {
          type: "cache:healthy",
          args: {
            paths: ["~/.maria/cache"],
          },
        },
      ],
    },
  },

  {
    id: "model-failover",
    name: "モデルフェイルオーバー",
    description: "無効なモデルから利用可能なモデルへ切替",
    match: {
      issueType: "MODEL_INVALID",
    },
    risk: {
      impact: "low",
      probability: "possible",
      score: 0.15,
    },
    requiresApproval: false,
    timeout: 5000,
    actions: {
      dryRun: [
        {
          type: "model:check",
          args: { current: true },
        },
        {
          type: "model:listAvailable",
          args: {},
        },
      ],
      apply: [
        {
          type: "config:backup",
          args: {
            key: "defaultModel",
            configPath: "~/.maria/config.json",
          },
        },
        {
          type: "config:setDefault",
          args: {
            key: "defaultModel",
            candidateOrder: [
              "gpt-4o", // OpenAI
              "claude-3-opus", // Anthropic
              "gemini-pro", // Google
              "llama-3", // Local (Ollama/LM Studio)
              "mistral-7b", // Fallback local
            ],
            configPath: "~/.maria/config.json",
          },
        },
      ],
      verify: [
        {
          type: "model:check",
          args: { current: true },
        },
      ],
      rollback: [
        {
          type: "config:restore",
          args: {
            key: "defaultModel",
            configPath: "~/.maria/config.json",
            backupPath: "~/.maria/config.json.bak",
          },
        },
      ],
    },
  },

  {
    id: "deps-install",
    name: "依存関係インストール",
    description: "不足している依存関係のインストール",
    match: {
      issueType: "DEPS_MISSING",
    },
    risk: {
      impact: "medium",
      probability: "rare",
      score: 0.2,
    },
    requiresApproval: false,
    timeout: 60000,
    allowedCommands: ["pnpm install", "npm install", "pnpm i", "npm i"],
    actions: {
      dryRun: [
        {
          type: "file:exists",
          args: { path: "package.json" },
        },
        {
          type: "shell:execute",
          args: {
            command: "pnpm install --dry-run",
            fallback: "npm install --dry-run",
          },
        },
      ],
      apply: [
        {
          type: "file:backup",
          args: {
            path: "pnpm-lock.yaml",
            optional: true,
          },
        },
        {
          type: "file:backup",
          args: {
            path: "package-lock.json",
            optional: true,
          },
        },
        {
          type: "shell:execute",
          args: {
            command: "pnpm install",
            fallback: "npm install",
            timeout: 60000,
          },
        },
      ],
      verify: [
        {
          type: "file:exists",
          args: { path: "node_modules" },
        },
      ],
      rollback: [
        {
          type: "file:restore",
          args: {
            path: "pnpm-lock.yaml",
            backupPath: "pnpm-lock.yaml.bak",
            optional: true,
          },
        },
        {
          type: "file:restore",
          args: {
            path: "package-lock.json",
            backupPath: "package-lock.json.bak",
            optional: true,
          },
        },
      ],
    },
  },

  {
    id: "permission-fix",
    name: "権限修正",
    description: "重要ファイルの権限設定",
    match: {
      issueType: "PERMISSION_ERROR",
    },
    risk: {
      impact: "low",
      probability: "rare",
      score: 0.2,
    },
    requiresApproval: false,
    timeout: 5000,
    actions: {
      dryRun: [
        {
          type: "file:checkPermissions",
          args: {
            path: ".env.local",
            expectedMode: "600",
          },
        },
        {
          type: "file:checkPermissions",
          args: {
            path: ".maria-session.json",
            expectedMode: "600",
            optional: true,
          },
        },
      ],
      apply: [
        {
          type: "file:chmod",
          args: {
            path: ".env.local",
            mode: "600",
          },
        },
        {
          type: "file:chmod",
          args: {
            path: ".maria-session.json",
            mode: "600",
            optional: true,
          },
        },
        {
          type: "file:chmod",
          args: {
            path: "~/.maria/config.json",
            mode: "600",
            optional: true,
          },
        },
      ],
      verify: [
        {
          type: "file:checkPermissions",
          args: {
            path: ".env.local",
            expectedMode: "600",
          },
        },
      ],
    },
  },
];
