name: 🐛 Bug Report
description: Report a bug in MARIA Platform
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out this form to help us understand and reproduce the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: Provide a clear and concise description of the bug
      placeholder: Describe what the bug is...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: List the steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: Describe what you expected to happen
      placeholder: What should happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: Describe what actually happened
      placeholder: What actually happens...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🌐 Environment
      description: Provide details about your environment
      placeholder: |
        - OS: [e.g., macOS 14.0, Windows 11, Ubuntu 22.04]
        - Node.js: [e.g., v18.17.0]
        - MARIA Version: [e.g., v1.3.0]
        - Terminal: [e.g., iTerm2, Windows Terminal, GNOME Terminal]
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: 📋 Error Logs
      description: Include any relevant error messages or logs
      placeholder: Paste error logs here...
      render: shell

  - type: dropdown
    id: severity
    attributes:
      label: 🔥 Severity
      description: How severe is this bug?
      options:
        - Low - Minor issue, workaround available
        - Medium - Moderate impact on functionality
        - High - Major functionality broken
        - Critical - System unusable or data loss
      default: 1
    validations:
      required: true

  - type: checkboxes
    id: repository-affected
    attributes:
      label: 📍 Repository Affected
      description: Which repositories are affected by this bug?
      options:
        - label: maria_code (private development)
        - label: maria (public distribution)
        - label: Both repositories

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 Additional Context
      description: Add any other context about the problem (screenshots, videos, etc.)
      placeholder: Any additional information that might be helpful...