name: 🚀 Feature Request
description: Suggest a new feature for MARIA Platform
title: "[FEATURE] "
labels: ["enhancement", "type/feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out this form to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: 📋 Feature Description
      description: Provide a clear and concise description of the feature you'd like to see
      placeholder: Brief description of the feature...
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: 🎯 User Story
      description: Describe the feature from a user's perspective
      placeholder: As a [user type], I want [goal] so that [benefit]...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: List the specific criteria that must be met for this feature to be considered complete
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: related-issues
    attributes:
      label: 🔗 Related Issues
      description: Link to any related issues or discussions
      placeholder: "#123, #456"

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority
      description: How important is this feature?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 1
    validations:
      required: true

  - type: checkboxes
    id: repository-scope
    attributes:
      label: 📍 Repository Scope
      description: Which repositories are affected by this feature?
      options:
        - label: maria_code (private development)
        - label: maria (public distribution)
        - label: Both repositories

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 Additional Context
      description: Add any other context, screenshots, or mockups about the feature request
      placeholder: Any additional information that might be helpful...