// AUTO-GENERATED by scripts/gen/command-types.mts -- DO NOT EDIT
declare module '@types/maria/commands' {
  /** 先頭スラ付きの正規コマンド名 */
  export type CommandName =
    | '/add-dir' |
    '/agents' |
    '/alias' |
    '/approval' |
    '/auth' |
    '/auto-organize' |
    '/avatar' |
    '/batch' |
    '/battlecard' |
    '/benchmark' |
    '/brain' |
    '/bug' |
    '/calc' |
    '/chain' |
    '/chart' |
    '/clear' |
    '/code' |
    '/compact' |
    '/config' |
    '/cost' |
    '/create-feature' |
    '/dashboard' |
    '/design' |
    '/design analyze' |
    '/design brief' |
    '/design web' |
    '/diagram' |
    '/doctor' |
    '/evolve' |
    '/exit' |
    '/export' |
    '/forget' |
    '/generate-docs' |
    '/gpu' |
    '/help' |
    '/hooks' |
    '/hotkey' |
    '/image' |
    '/init' |
    '/l2r' |
    '/language' |
    '/lint' |
    '/llm' |
    '/login' |
    '/logout' |
    '/mcp' |
    '/memory' |
    '/memory-status' |
    '/migrate-installer' |
    '/model' |
    '/monitor' |
    '/optimize-structure' |
    '/paper' |
    '/permissions' |
    '/pilot-setup' |
    '/plot' |
    '/pm' |
    '/pm analyze' |
    '/pm export' |
    '/pm gantt' |
    '/pm sow' |
    '/pm update' |
    '/pr-comments' |
    '/recall' |
    '/release-notes' |
    '/remember' |
    '/resume' |
    '/review' |
    '/sales-dashboard' |
    '/save' |
    '/saveto' |
    '/search' |
    '/security-review' |
    '/settings' |
    '/setup' |
    '/setup-project' |
    '/shell' |
    '/signin' |
    '/signout' |
    '/snippet' |
    '/solve' |
    '/status' |
    '/stream' |
    '/suggest' |
    '/template' |
    '/templates' |
    '/terminal-setup' |
    '/test' |
    '/tune' |
    '/typecheck' |
    '/update' |
    '/upgrade' |
    '/version' |
    '/video' |
    '/vim' |
    '/voice'
  ;

  /** 先頭スラ無しの素の名称 */
  export type CommandBaseName =
    | 'add-dir' |
    'agents' |
    'alias' |
    'approval' |
    'auth' |
    'auto-organize' |
    'avatar' |
    'batch' |
    'battlecard' |
    'benchmark' |
    'brain' |
    'bug' |
    'calc' |
    'chain' |
    'chart' |
    'clear' |
    'code' |
    'compact' |
    'config' |
    'cost' |
    'create-feature' |
    'dashboard' |
    'design' |
    'design analyze' |
    'design brief' |
    'design web' |
    'diagram' |
    'doctor' |
    'evolve' |
    'exit' |
    'export' |
    'forget' |
    'generate-docs' |
    'gpu' |
    'help' |
    'hooks' |
    'hotkey' |
    'image' |
    'init' |
    'l2r' |
    'language' |
    'lint' |
    'llm' |
    'login' |
    'logout' |
    'mcp' |
    'memory' |
    'memory-status' |
    'migrate-installer' |
    'model' |
    'monitor' |
    'optimize-structure' |
    'paper' |
    'permissions' |
    'pilot-setup' |
    'plot' |
    'pm' |
    'pm analyze' |
    'pm export' |
    'pm gantt' |
    'pm sow' |
    'pm update' |
    'pr-comments' |
    'recall' |
    'release-notes' |
    'remember' |
    'resume' |
    'review' |
    'sales-dashboard' |
    'save' |
    'saveto' |
    'search' |
    'security-review' |
    'settings' |
    'setup' |
    'setup-project' |
    'shell' |
    'signin' |
    'signout' |
    'snippet' |
    'solve' |
    'status' |
    'stream' |
    'suggest' |
    'template' |
    'templates' |
    'terminal-setup' |
    'test' |
    'tune' |
    'typecheck' |
    'update' |
    'upgrade' |
    'version' |
    'video' |
    'vim' |
    'voice'
  ;

  /** aliases: 先頭スラ付きの別名（存在しなければ never） */
  export type CommandAlias =
    | '/approve' |
    '/auto-evolve' |
    '/dash' |
    '/device' |
    '/evolution' |
    '/graphics' |
    '/learn' |
    '/ltr' |
    '/m' |
    '/mem-status' |
    '/models' |
    '/rank' |
    '/sh' |
    '/write' |
    '/writeto'
  ;

  /** 許容されるトークン（正規名／別名／素の名称） */
  export type CommandAnyName = CommandName | CommandAlias | CommandBaseName;

  /** 実行時にも使えるリスト（readonly） */
  export const COMMAND_NAMES: readonly CommandName[];
  export const COMMAND_ALIASES: readonly CommandAlias[];
  export const COMMAND_BASENAMES: readonly CommandBaseName[];

  /** alias -> canonical への解決表（存在すれば） */
  export const ALIAS_TARGETS: Readonly<Record<CommandAlias, CommandName>>;
}
