/**
 * MARIA.md Template Generator
 * Ensures standardized, high-quality documentation output
 */

import * as path from "path";
import type { InitSummary } from "./types";
import type { MonorepoInfo } from "./phase-a";
import type { VisualInsights } from "./insights-tables";
import type { DeepAppendix } from "./deep-appendix";
import { formatInsightsForMarkdown } from "./insights-tables";
import { formatAppendixForMarkdown } from "./deep-appendix";

export interface MariaTemplateData {
  projectName: string;
  projectPath: string;
  timestamp: string;
  summary?: InitSummary;
  monorepo?: MonorepoInfo;
  insights?: VisualInsights;
  appendix?: DeepAppendix;
  errors?: string[];
}

/**
 * Generate standardized MARIA.md content
 * Guarantees minimum quality standards even on errors
 */
export function generateMariaMd(data: MariaTemplateData): string {
  const sections: string[] = [];

  // Header
  sections.push(generateHeader(data));

  // Table of Contents
  sections.push(generateTableOfContents());

  // Overview (Required Section)
  sections.push(generateOverview(data));

  // Quick Start (Required Section)
  sections.push(generateQuickStart(data));

  // Commands (Required Section)
  sections.push(generateCommands(data));

  // Architecture (Required Section)
  sections.push(generateArchitecture(data));

  // Configuration (Required Section)
  sections.push(generateConfiguration(data));

  // Testing (Required Section)
  sections.push(generateTesting(data));

  // Development Workflow
  sections.push(generateDevelopmentWorkflow(data));

  // Visual Insights (if available)
  if (data.insights) {
    sections.push(formatInsightsForMarkdown(data.insights));
  }

  // Troubleshooting
  sections.push(generateTroubleshooting(data));

  // Deep Appendix (if available)
  if (data.appendix) {
    sections.push(formatAppendixForMarkdown(data.appendix));
  }

  // Footer with metadata
  sections.push(generateFooter(data));

  return sections.join("\n\n---\n\n");
}

/**
 * Generate header section
 */
function generateHeader(data: MariaTemplateData): string {
  const lines: string[] = [];

  lines.push(`# ${data.projectName || "Project"} - MARIA Documentation`);
  lines.push("");
  lines.push(
    `> AI-powered project documentation generated by MARIA /init command`,
  );
  lines.push(`> Generated: ${data.timestamp}`);
  lines.push(`> Path: ${data.projectPath}`);

  if (data.errors && data.errors.length > 0) {
    lines.push("");
    lines.push(
      "> ⚠️ **Note**: Documentation generated with partial data due to scan errors.",
    );
  }

  return lines.join("\n");
}

/**
 * Generate table of contents
 */
function generateTableOfContents(): string {
  const lines: string[] = [];

  lines.push("## Table of Contents");
  lines.push("");
  lines.push("- [Overview](#overview)");
  lines.push("- [Quick Start](#quick-start)");
  lines.push("- [Commands](#commands)");
  lines.push("- [Architecture](#architecture)");
  lines.push("- [Configuration](#configuration)");
  lines.push("- [Testing](#testing)");
  lines.push("- [Development Workflow](#development-workflow)");
  lines.push("- [Troubleshooting](#troubleshooting)");
  lines.push("- [Visual Analysis](#visual-analysis)");
  lines.push("- [Deep Technical Appendix](#deep-technical-appendix)");

  return lines.join("\n");
}

/**
 * Generate Overview section (Required, min 300 chars)
 */
function generateOverview(data: MariaTemplateData): string {
  const lines: string[] = [];

  lines.push("## Overview");
  lines.push("");

  if (data.summary?.description) {
    lines.push(data.summary.description);
  } else {
    // Fallback content to ensure minimum character count
    lines.push(
      `${data.projectName || "This project"} is a software application built with modern development practices.`,
    );
    lines.push("");
  }

  // Project type and structure
  if (data.monorepo && data.monorepo.type !== "single") {
    lines.push(`### Project Structure`);
    lines.push("");
    lines.push(
      `This is a **${data.monorepo.type}** monorepo containing ${data.monorepo.stats.totalWorkspaces} workspaces:`,
    );
    lines.push(
      `- **Applications**: ${data.monorepo.structure.apps.length} apps`,
    );
    lines.push(
      `- **Libraries**: ${data.monorepo.structure.libs.length} libraries`,
    );
    lines.push(`- **Tools**: ${data.monorepo.structure.tools.length} tools`);
    lines.push(
      `- **Configurations**: ${data.monorepo.structure.configs.length} config packages`,
    );
  } else {
    lines.push("### Project Type");
    lines.push("");
    lines.push(
      "This is a standalone application project with a single package structure.",
    );
  }

  // Technology stack summary
  if (data.summary?.techStack) {
    lines.push("");
    lines.push("### Technology Stack");
    lines.push("");
    if (data.summary.techStack.languages.size > 0) {
      lines.push(
        `- **Languages**: ${Array.from(data.summary.techStack.languages).join(", ")}`,
      );
    }
    if (data.summary.techStack.frameworks.size > 0) {
      lines.push(
        `- **Frameworks**: ${Array.from(data.summary.techStack.frameworks).join(", ")}`,
      );
    }
    if (data.summary.techStack.packageManager) {
      lines.push(
        `- **Package Manager**: ${data.summary.techStack.packageManager}`,
      );
    }
  }

  // Statistics
  if (data.summary?.stats) {
    lines.push("");
    lines.push("### Project Statistics");
    lines.push("");
    lines.push(`- Total files analyzed: ${data.summary.stats.filesScanned}`);
    lines.push(`- Lines of code: ${data.summary.stats.linesOfCode || "N/A"}`);
    lines.push(`- Test coverage: ${data.summary.stats.testCoverage || "N/A"}`);
  }

  // Ensure minimum character count
  const content = lines.join("\n");
  if (content.length < 300) {
    lines.push("");
    lines.push(
      "This project follows industry best practices for code organization, testing, and deployment. ",
    );
    lines.push(
      "It includes comprehensive tooling for development, testing, and continuous integration. ",
    );
    lines.push(
      "The codebase is structured to support scalability and maintainability.",
    );
  }

  return lines.join("\n");
}

/**
 * Generate Quick Start section (Required, min 200 chars)
 */
function generateQuickStart(data: MariaTemplateData): string {
  const lines: string[] = [];

  lines.push("## Quick Start");
  lines.push("");
  lines.push(
    "Follow these steps to get the project running on your local machine.",
  );
  lines.push("");

  // Prerequisites
  lines.push("### Prerequisites");
  lines.push("");
  lines.push("```bash");
  lines.push("# Required: Node.js 20.10.0 or higher");
  lines.push("node --version");
  lines.push("");
  lines.push(
    `# Required: ${data.summary?.techStack?.packageManager || "npm"} package manager`,
  );
  lines.push(`${data.summary?.techStack?.packageManager || "npm"} --version`);
  lines.push("```");
  lines.push("");

  // Installation
  lines.push("### Installation");
  lines.push("");
  lines.push("```bash");
  lines.push("# Clone the repository");
  lines.push("git clone <repository-url>");
  lines.push(`cd ${data.projectName || "project"}`);
  lines.push("");
  lines.push("# Install dependencies");
  lines.push(`${data.summary?.techStack?.packageManager || "npm"} install`);
  lines.push("```");
  lines.push("");

  // Running the project
  lines.push("### Running the Project");
  lines.push("");
  lines.push("```bash");
  lines.push("# Development mode");
  lines.push(`${data.summary?.techStack?.packageManager || "npm"} run dev`);
  lines.push("");
  lines.push("# Production build");
  lines.push(`${data.summary?.techStack?.packageManager || "npm"} run build`);
  lines.push("");
  lines.push("# Run tests");
  lines.push(`${data.summary?.techStack?.packageManager || "npm"} test`);
  lines.push("```");

  return lines.join("\n");
}

/**
 * Generate Commands section (Required, min 500 chars)
 */
function generateCommands(data: MariaTemplateData): string {
  const lines: string[] = [];
  const pm = data.summary?.techStack?.packageManager || "npm";

  lines.push("## Commands");
  lines.push("");
  lines.push(
    "This section lists all available commands for development, testing, and deployment.",
  );
  lines.push("");

  // Development commands
  lines.push("### Development Commands");
  lines.push("");
  lines.push("| Command | Description | Usage |");
  lines.push("|---------|-------------|-------|");
  lines.push(`| dev | Start development server | \`${pm} run dev\` |`);
  lines.push(`| build | Build for production | \`${pm} run build\` |`);
  lines.push(`| start | Start production server | \`${pm} start\` |`);
  lines.push(`| watch | Watch for file changes | \`${pm} run watch\` |`);
  lines.push("");

  // Testing commands
  lines.push("### Testing Commands");
  lines.push("");
  lines.push("| Command | Description | Usage |");
  lines.push("|---------|-------------|-------|");
  lines.push(`| test | Run all tests | \`${pm} test\` |`);
  lines.push(`| test:unit | Run unit tests | \`${pm} run test:unit\` |`);
  lines.push(
    `| test:integration | Run integration tests | \`${pm} run test:integration\` |`,
  );
  lines.push(
    `| test:coverage | Generate coverage report | \`${pm} run test:coverage\` |`,
  );
  lines.push("");

  // Quality commands
  lines.push("### Code Quality Commands");
  lines.push("");
  lines.push("| Command | Description | Usage |");
  lines.push("|---------|-------------|-------|");
  lines.push(`| lint | Run ESLint | \`${pm} run lint\` |`);
  lines.push(`| lint:fix | Fix linting issues | \`${pm} run lint:fix\` |`);
  lines.push(
    `| type-check | Run TypeScript checks | \`${pm} run type-check\` |`,
  );
  lines.push(`| format | Format code with Prettier | \`${pm} run format\` |`);
  lines.push("");

  // Utility commands
  lines.push("### Utility Commands");
  lines.push("");
  lines.push("| Command | Description | Usage |");
  lines.push("|---------|-------------|-------|");
  lines.push(`| clean | Clean build artifacts | \`${pm} run clean\` |`);
  lines.push(`| deps:check | Check dependencies | \`${pm} run deps:check\` |`);
  lines.push(`| docs | Generate documentation | \`${pm} run docs\` |`);

  return lines.join("\n");
}

/**
 * Generate Architecture section (Required, min 400 chars)
 */
function generateArchitecture(data: MariaTemplateData): string {
  const lines: string[] = [];

  lines.push("## Architecture");
  lines.push("");
  lines.push(
    "This section describes the high-level architecture and design patterns used in the project.",
  );
  lines.push("");

  // Project structure
  lines.push("### Directory Structure");
  lines.push("");
  lines.push("```");

  if (data.monorepo && data.monorepo.type !== "single") {
    // Monorepo structure
    lines.push(".");
    lines.push("├── apps/              # Application packages");
    lines.push("├── packages/          # Shared libraries");
    lines.push("├── tools/             # Build and dev tools");
    lines.push("├── configs/           # Shared configurations");
    lines.push("├── docs/              # Documentation");
    lines.push("├── scripts/           # Build and CI scripts");
    lines.push("├── package.json       # Root package.json");
    lines.push(
      `└── ${data.monorepo.packageManager === "pnpm" ? "pnpm-workspace.yaml" : "lerna.json"}  # Workspace config`,
    );
  } else {
    // Standard structure
    lines.push(".");
    lines.push("├── src/               # Source code");
    lines.push("│   ├── components/    # UI components");
    lines.push("│   ├── services/      # Business logic");
    lines.push("│   ├── utils/         # Utility functions");
    lines.push("│   └── types/         # TypeScript types");
    lines.push("├── tests/             # Test files");
    lines.push("├── docs/              # Documentation");
    lines.push("├── scripts/           # Build scripts");
    lines.push("└── package.json       # Package configuration");
  }

  lines.push("```");
  lines.push("");

  // Design patterns
  lines.push("### Design Patterns");
  lines.push("");
  lines.push(
    "The project implements several design patterns for maintainability:",
  );
  lines.push("");
  lines.push(
    "- **Separation of Concerns**: Business logic is separated from presentation",
  );
  lines.push(
    "- **Dependency Injection**: Services are injected rather than directly imported",
  );
  lines.push(
    "- **Factory Pattern**: Complex object creation is handled by factory functions",
  );
  lines.push(
    "- **Observer Pattern**: Event-driven communication between components",
  );
  lines.push("");

  // Data flow
  lines.push("### Data Flow");
  lines.push("");
  lines.push("Data flows through the application in a unidirectional manner:");
  lines.push("");
  lines.push("1. **Input Layer**: User interactions or API requests");
  lines.push("2. **Service Layer**: Business logic processing");
  lines.push("3. **Data Layer**: Database or external API interactions");
  lines.push("4. **Presentation Layer**: UI updates or API responses");

  return lines.join("\n");
}

/**
 * Generate Configuration section (Required, min 200 chars)
 */
function generateConfiguration(data: MariaTemplateData): string {
  const lines: string[] = [];

  lines.push("## Configuration");
  lines.push("");
  lines.push(
    "This section covers the configuration requirements and options for the project.",
  );
  lines.push("");

  // Environment variables
  lines.push("### Environment Variables");
  lines.push("");
  lines.push(
    "Create a `.env` file in the root directory with the following variables:",
  );
  lines.push("");
  lines.push("```bash");
  lines.push("# Application");
  lines.push("NODE_ENV=development");
  lines.push("PORT=3000");
  lines.push("");
  lines.push("# Database");
  lines.push("DATABASE_URL=your_database_url");
  lines.push("");
  lines.push("# API Keys");
  lines.push("API_KEY=your_api_key");
  lines.push("SECRET_KEY=your_secret_key");
  lines.push("```");
  lines.push("");

  // Build configuration
  lines.push("### Build Configuration");
  lines.push("");
  lines.push(
    "The build process can be configured through the following files:",
  );
  lines.push("");
  lines.push("- `tsconfig.json`: TypeScript compilation options");
  lines.push(
    "- `vite.config.ts` or `webpack.config.js`: Bundler configuration",
  );
  lines.push("- `.eslintrc.js`: Linting rules");
  lines.push("- `.prettierrc`: Code formatting rules");

  return lines.join("\n");
}

/**
 * Generate Testing section (Required, min 150 chars)
 */
function generateTesting(data: MariaTemplateData): string {
  const lines: string[] = [];
  const pm = data.summary?.techStack?.packageManager || "npm";

  lines.push("## Testing");
  lines.push("");
  lines.push(
    "The project includes comprehensive testing to ensure code quality and reliability.",
  );
  lines.push("");

  // Test types
  lines.push("### Test Types");
  lines.push("");
  lines.push("- **Unit Tests**: Test individual functions and components");
  lines.push("- **Integration Tests**: Test component interactions");
  lines.push("- **E2E Tests**: Test complete user workflows");
  lines.push("");

  // Running tests
  lines.push("### Running Tests");
  lines.push("");
  lines.push("```bash");
  lines.push("# Run all tests");
  lines.push(`${pm} test`);
  lines.push("");
  lines.push("# Run tests in watch mode");
  lines.push(`${pm} test:watch`);
  lines.push("");
  lines.push("# Generate coverage report");
  lines.push(`${pm} test:coverage`);
  lines.push("```");
  lines.push("");

  // Test structure
  lines.push("### Test Structure");
  lines.push("");
  lines.push(
    "Tests are organized following the same structure as the source code:",
  );
  lines.push("");
  lines.push("```");
  lines.push("tests/");
  lines.push("├── unit/           # Unit tests");
  lines.push("├── integration/    # Integration tests");
  lines.push("└── e2e/           # End-to-end tests");
  lines.push("```");

  return lines.join("\n");
}

/**
 * Generate Development Workflow section
 */
function generateDevelopmentWorkflow(data: MariaTemplateData): string {
  const lines: string[] = [];
  const pm = data.summary?.techStack?.packageManager || "npm";

  lines.push("## Development Workflow");
  lines.push("");
  lines.push("### Branch Strategy");
  lines.push("");
  lines.push("- `main`: Production-ready code");
  lines.push("- `develop`: Integration branch for features");
  lines.push("- `feature/*`: Feature development branches");
  lines.push("- `hotfix/*`: Emergency fixes for production");
  lines.push("");

  lines.push("### Development Process");
  lines.push("");
  lines.push("1. **Create Feature Branch**");
  lines.push("   ```bash");
  lines.push("   git checkout -b feature/your-feature");
  lines.push("   ```");
  lines.push("");
  lines.push("2. **Make Changes**");
  lines.push("   - Write code following project conventions");
  lines.push("   - Add tests for new functionality");
  lines.push("   - Update documentation as needed");
  lines.push("");
  lines.push("3. **Run Quality Checks**");
  lines.push("   ```bash");
  lines.push(`   ${pm} run lint`);
  lines.push(`   ${pm} run type-check`);
  lines.push(`   ${pm} test`);
  lines.push("   ```");
  lines.push("");
  lines.push("4. **Commit Changes**");
  lines.push("   ```bash");
  lines.push("   git add .");
  lines.push('   git commit -m "feat: add new feature"');
  lines.push("   ```");
  lines.push("");
  lines.push("5. **Push and Create PR**");
  lines.push("   ```bash");
  lines.push("   git push origin feature/your-feature");
  lines.push("   # Create pull request on GitHub/GitLab");
  lines.push("   ```");

  return lines.join("\n");
}

/**
 * Generate Troubleshooting section
 */
function generateTroubleshooting(data: MariaTemplateData): string {
  const lines: string[] = [];
  const pm = data.summary?.techStack?.packageManager || "npm";

  lines.push("## Troubleshooting");
  lines.push("");
  lines.push("### Common Issues and Solutions");
  lines.push("");

  // Installation issues
  lines.push("#### Installation Failures");
  lines.push("");
  lines.push("**Problem**: Dependencies fail to install");
  lines.push("**Solution**:");
  lines.push("```bash");
  lines.push("# Clear cache and reinstall");
  lines.push(`${pm} cache clean --force`);
  lines.push("rm -rf node_modules package-lock.json");
  lines.push(`${pm} install`);
  lines.push("```");
  lines.push("");

  // Build issues
  lines.push("#### Build Errors");
  lines.push("");
  lines.push("**Problem**: TypeScript or build errors");
  lines.push("**Solution**:");
  lines.push("```bash");
  lines.push("# Clean and rebuild");
  lines.push(`${pm} run clean`);
  lines.push(`${pm} run build`);
  lines.push("```");
  lines.push("");

  // Test failures
  lines.push("#### Test Failures");
  lines.push("");
  lines.push("**Problem**: Tests fail unexpectedly");
  lines.push("**Solution**:");
  lines.push("- Ensure all dependencies are installed");
  lines.push("- Check for environment variable requirements");
  lines.push("- Clear test cache if using Jest");
  lines.push("");

  // Performance issues
  lines.push("#### Performance Issues");
  lines.push("");
  lines.push("**Problem**: Slow build or runtime performance");
  lines.push("**Solution**:");
  lines.push("- Enable production optimizations");
  lines.push("- Check for memory leaks");
  lines.push("- Profile the application");

  return lines.join("\n");
}

/**
 * Generate footer with metadata
 */
function generateFooter(data: MariaTemplateData): string {
  const lines: string[] = [];

  lines.push("## Metadata");
  lines.push("");
  lines.push("```yaml");
  lines.push(`generated_by: MARIA /init command`);
  lines.push(`version: 3.4.2`);
  lines.push(`timestamp: ${data.timestamp}`);
  lines.push(`project_path: ${data.projectPath}`);

  if (data.summary?.stats) {
    lines.push(`files_analyzed: ${data.summary.stats.filesScanned}`);
    lines.push(`scan_duration: ${data.summary.stats.scanDuration}ms`);
  }

  if (data.errors && data.errors.length > 0) {
    lines.push(`errors_encountered: ${data.errors.length}`);
  }

  lines.push("```");
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(
    "*This documentation was automatically generated by MARIA. For updates, run `maria /init` again.*",
  );

  return lines.join("\n");
}

/**
 * Fallback MARIA.md generator for error scenarios
 */
export function generateFallbackMariaMd(
  error: Error,
  projectPath: string,
): string {
  const data: MariaTemplateData = {
    projectName: path.basename(projectPath),
    projectPath,
    timestamp: new Date().toISOString(),
    errors: [error.message],
  };

  return generateMariaMd(data);
}
