import { describe, it, expect } from "vitest";
import { generateArtifacts } from "../../artifacts";
import type { InitFinding, InitSummary } from "../../types";

describe("Artifact Generation", () => {
  const mockSummary: InitSummary = {
    package: {
      name: "@test/maria",
      version: "3.0.0",
      type: "module",
      scripts: ["build", "test", "lint"],
      hasPostinstall: false,
      bin: { maria: "bin/maria" },
      main: "dist/index.js",
      exports: { ".": "./dist/index.js" },
      dependencies: ["chalk", "prompts"],
      devDependencies: ["typescript", "vitest"],
    },
    entries: ["src/cli.ts", "src/index.ts"],
    configs: ["tsconfig.json", ".eslintrc.cjs", "vitest.config.ts"],
    scriptsCount: 12,
    warnings: [
      {
        id: "script.missing.smoke",
        level: "low",
        file: "package.json",
        message: "Missing test:smoke script - add for CI validation",
      },
      {
        id: "config.missing.eslint",
        level: "medium",
        file: ".",
        message: "ESLint config not found - consider adding strict rules",
      },
    ],
  };

  const mockFindings: InitFinding[] = [
    {
      file: "package.json",
      kind: "read",
      head: '{ "name": "@test/maria", "version": "3.0.0" }',
      meta: { name: "@test/maria", version: "3.0.0" },
    },
    {
      file: "src/cli.ts",
      kind: "entry",
      head: '#!/usr/bin/env node\nimport { cli } from "./index";\ncli();',
    },
    {
      file: "tsconfig.json",
      kind: "config",
      head: '{ "compilerOptions": { "target": "ES2022" } }',
    },
  ];

  it("generates all 4 artifacts", () => {
    const artifacts = generateArtifacts(
      mockSummary,
      mockFindings,
      Date.now() - 1000,
    );

    expect(typeof artifacts.claudeMd).toBe("string");
    expect(typeof artifacts.initReportMd).toBe("string");
    expect(typeof artifacts.depMapJson).toBe("object");
    expect(typeof artifacts.initSummaryTxt).toBe("string");
  });

  it("generates MARIA.md with project info", () => {
    const artifacts = generateArtifacts(mockSummary, mockFindings);

    expect(artifacts.claudeMd).toContain(
      "# Project Guide (Generated by /init)",
    );
    expect(artifacts.claudeMd).toContain("@test/maria");
    expect(artifacts.claudeMd).toContain("3.0.0");
    expect(artifacts.claudeMd).toContain("ESM");
    expect(artifacts.claudeMd).toContain("src/cli.ts");
    expect(artifacts.claudeMd).toContain("Known Issues");
    expect(artifacts.claudeMd).toContain("Recommended Actions");
  });

  it("includes warnings in MARIA.md", () => {
    const artifacts = generateArtifacts(mockSummary, mockFindings);

    expect(artifacts.claudeMd).toContain(
      "🔵 **LOW**: Missing test:smoke script",
    );
    expect(artifacts.claudeMd).toContain(
      "🟡 **MEDIUM**: ESLint config not found",
    );
  });

  it("generates detailed INIT_REPORT.md", () => {
    const artifacts = generateArtifacts(mockSummary, mockFindings);

    expect(artifacts.initReportMd).toContain("# INIT REPORT (Raw Findings)");
    expect(artifacts.initReportMd).toContain("Executive Summary");
    expect(artifacts.initReportMd).toContain("Performance Metrics");
    expect(artifacts.initReportMd).toContain("File Analysis Results");
    expect(artifacts.initReportMd).toContain("### READ — package.json");
  });

  it("generates machine-readable DEPENDENCY_MAP.json", () => {
    const artifacts = generateArtifacts(mockSummary, mockFindings);

    expect(artifacts.depMapJson).toHaveProperty("package");
    expect(artifacts.depMapJson).toHaveProperty("structure");
    expect(artifacts.depMapJson).toHaveProperty("warnings");
    expect(artifacts.depMapJson).toHaveProperty("metrics");
    expect(artifacts.depMapJson).toHaveProperty("generated");

    expect(artifacts.depMapJson.package.name).toBe("@test/maria");
    expect(artifacts.depMapJson.structure.entries).toContain("src/cli.ts");
    expect(artifacts.depMapJson.warnings).toHaveLength(2);
  });

  it("generates executive summary text", () => {
    const artifacts = generateArtifacts(mockSummary, mockFindings);

    expect(artifacts.initSummaryTxt).toContain("INIT SUMMARY");
    expect(artifacts.initSummaryTxt).toContain("repo: @test/maria");
    expect(artifacts.initSummaryTxt).toContain("scripts: 3");
    expect(artifacts.initSummaryTxt).toContain("warnings (2):");
    expect(artifacts.initSummaryTxt).toContain("immediate actions:");
  });

  it("handles empty/minimal data gracefully", () => {
    const minimalSummary: InitSummary = {
      package: { scripts: [], hasPostinstall: false },
      entries: [],
      configs: [],
      scriptsCount: 0,
      warnings: [],
    };

    const artifacts = generateArtifacts(minimalSummary, [], Date.now());

    expect(artifacts.claudeMd).toContain("Unknown Project");
    expect(artifacts.claudeMd).toContain("_No warnings detected_");
    expect(artifacts.depMapJson.package.name).toBeNull();
    expect(artifacts.initSummaryTxt).toContain("warnings (0):");
  });

  it("detects technology stack correctly", () => {
    const findingsWithStack: InitFinding[] = [
      ...mockFindings,
      { file: "vitest.config.ts", kind: "config", head: "export default {}" },
      { file: "tsup.config.ts", kind: "config", head: "export default {}" },
      { file: "pnpm-lock.yaml", kind: "config", head: "lockfileVersion: 6.0" },
    ];

    const artifacts = generateArtifacts(mockSummary, findingsWithStack);

    expect(artifacts.claudeMd).toContain("TypeScript");
    expect(artifacts.claudeMd).toContain("pnpm");
    expect(artifacts.claudeMd).toContain("tsup");
    expect(artifacts.claudeMd).toContain("Vitest");
    expect(artifacts.claudeMd).toContain("MARIA Platform");
  });

  it("formats warnings by severity", () => {
    const summaryWithMixedWarnings: InitSummary = {
      ...mockSummary,
      warnings: [
        { id: "low", level: "low", file: "test", message: "Low warning" },
        { id: "high", level: "high", file: "test", message: "High warning" },
        {
          id: "medium",
          level: "medium",
          file: "test",
          message: "Medium warning",
        },
      ],
    };

    const artifacts = generateArtifacts(summaryWithMixedWarnings, mockFindings);

    const lines = artifacts.claudeMd.split("\n");
    const warningsSection = lines.slice(
      lines.findIndex((l) => l.includes("Known Issues")),
      lines.findIndex((l) => l.includes("Recommended Actions")),
    );

    // High warnings should come first
    const highIndex = warningsSection.findIndex((l) =>
      l.includes("🔴 **HIGH**"),
    );
    const mediumIndex = warningsSection.findIndex((l) =>
      l.includes("🟡 **MEDIUM**"),
    );
    const lowIndex = warningsSection.findIndex((l) => l.includes("🔵 **LOW**"));

    expect(highIndex).toBeLessThan(mediumIndex);
    expect(mediumIndex).toBeLessThan(lowIndex);
  });

  it("generates actionable recommendations", () => {
    const artifacts = generateArtifacts(mockSummary, mockFindings);

    expect(artifacts.claudeMd).toContain("## Recommended Actions");
    expect(artifacts.claudeMd).toContain("1. "); // Numbered list
    expect(artifacts.initSummaryTxt).toContain("immediate actions:");
  });

  it("includes correct metrics in all artifacts", () => {
    const startTime = Date.now() - 5000; // 5 seconds ago
    const artifacts = generateArtifacts(mockSummary, mockFindings, startTime);

    // Check metrics in JSON
    expect(artifacts.depMapJson.metrics.scan_ms_total).toBeGreaterThan(4000);
    expect(artifacts.depMapJson.metrics.files_read).toBe(3); // mockFindings with content
    expect(artifacts.depMapJson.metrics.warnings_total).toBe(2);

    // Check metrics in report
    expect(artifacts.initReportMd).toContain("Scan time:");
    expect(artifacts.initReportMd).toContain("Files read: 3");

    // Check metrics in summary
    expect(artifacts.initSummaryTxt).toContain("scan time:");
    expect(artifacts.initSummaryTxt).toContain("files read: 3");
  });
});
