/**
 * Template Repository for fallback content
 */

export class TemplateRepo {
  constructor(private templates: Record<string, string>) {}

  async get(key: string): Promise<string> {
    const template = this.templates[key];
    if (!template) {
      throw new Error(`Template not found: ${key}`);
    }
    return template;
  }

  has(key: string): boolean {
    return key in this.templates;
  }

  list(): string[] {
    return Object.keys(this.templates);
  }
}

export function defaultTemplates(): TemplateRepo {
  return new TemplateRepo({
    "hello-html": BASIC_HELLO_HTML,
    "basic-html-index": BASIC_TETRIS_INDEX_HTML,
    "error-page": ERROR_PAGE_HTML,
    "basic-typescript": BASIC_TYPESCRIPT,
    "basic-javascript": BASIC_JAVASCRIPT,
  });
}

const BASIC_HELLO_HTML = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>Hello from MARIA</title>
</head>
<body>
  <h1>Hello World</h1>
  <p>Generated by MARIA Code Assistant</p>
</body>
</html>`;

const ERROR_PAGE_HTML = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>Error</title>
  <style>
    body { font-family: system-ui; padding: 2rem; background: #f3f4f6; }
    .error { background: white; border-radius: 8px; padding: 2rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    h1 { color: #ef4444; }
  </style>
</head>
<body>
  <div class="error">
    <h1>Something went wrong</h1>
    <p>Please try again later.</p>
  </div>
</body>
</html>`;

const BASIC_TETRIS_INDEX_HTML = `<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>Tetris</title>
  <style>
    body{margin:0;background:#0b1220;color:#e5e7eb;font-family:system-ui,sans-serif;display:flex;justify-content:center;align-items:center;min-height:100vh}
    .game{display:flex;gap:2rem;align-items:flex-start}
    canvas{background:#111827;border:2px solid #374151;box-shadow:0 4px 6px -1px rgba(0,0,0,0.1)}
    .panel{background:#1f2937;padding:1.5rem;border-radius:0.5rem;min-width:200px}
    .panel h1{margin:0 0 1rem;font-size:1.5rem}
    .panel p{margin:0.5rem 0;font-size:0.875rem}
    .kbd{display:inline-block;padding:0.25rem 0.5rem;background:#374151;border-radius:0.25rem;font-size:0.75rem;margin:0 0.125rem}
    .score{font-size:1.25rem;font-weight:bold;color:#60a5fa}
  </style>
</head>
<body>
  <div class="game">
    <canvas id="board" width="240" height="480"></canvas>
    <div class="panel">
      <h1>🎮 Tetris</h1>
      <p>操作方法:</p>
      <p><span class="kbd">←</span><span class="kbd">→</span> 移動</p>
      <p><span class="kbd">↑</span> 回転</p>
      <p><span class="kbd">↓</span> 落下</p>
      <p><span class="kbd">Space</span> 即落下</p>
      <hr style="border:none;border-top:1px solid #374151;margin:1rem 0">
      <p class="score">Score: <span id="score">0</span></p>
      <p>Lines: <span id="lines">0</span></p>
      <p>Level: <span id="level">1</span></p>
    </div>
  </div>
<script>
(()=>{
// Game constants
const COLS=10,ROWS=20,SIZE=24;
const canvas=document.getElementById('board');
const ctx=canvas.getContext('2d');
const scoreEl=document.getElementById('score');
const linesEl=document.getElementById('lines');
const levelEl=document.getElementById('level');

// Colors for pieces
const COLORS=["#000","#60a5fa","#f472b6","#34d399","#fbbf24","#a78bfa","#f87171","#22d3ee"];

// Tetromino shapes
const SHAPES={
  I:[[1,1,1,1]],
  J:[[2,0,0],[2,2,2]],
  L:[[0,0,3],[3,3,3]],
  O:[[4,4],[4,4]],
  S:[[0,5,5],[5,5,0]],
  T:[[0,6,0],[6,6,6]],
  Z:[[7,7,0],[0,7,7]]
};

// Game state
let grid=Array(ROWS).fill().map(()=>Array(COLS).fill(0));
let current=null;
let score=0,lines=0,level=1;
let dropTime=1000;
let lastDrop=0;
let gameOver=false;

// Initialize
function init(){
  grid=Array(ROWS).fill().map(()=>Array(COLS).fill(0));
  score=lines=0;level=1;
  dropTime=1000;
  gameOver=false;
  current=spawn();
  updateDisplay();
}

// Spawn new piece
function spawn(){
  const types=Object.keys(SHAPES);
  const type=types[Math.floor(Math.random()*types.length)];
  const shape=SHAPES[type].map(row=>[...row]);
  return {
    shape,
    x:Math.floor((COLS-shape[0].length)/2),
    y:0,
    color:Object.keys(SHAPES).indexOf(type)+1
  };
}

// Draw cell
function drawCell(x,y,color){
  if(color){
    ctx.fillStyle=COLORS[color];
    ctx.fillRect(x*SIZE,y*SIZE,SIZE-1,SIZE-1);
    // Add highlight
    ctx.fillStyle='rgba(255,255,255,0.1)';
    ctx.fillRect(x*SIZE,y*SIZE,SIZE-1,4);
  }else{
    ctx.fillStyle='#0f172a';
    ctx.fillRect(x*SIZE,y*SIZE,SIZE-1,SIZE-1);
  }
}

// Draw game
function draw(){
  // Clear
  ctx.fillStyle='#0b1220';
  ctx.fillRect(0,0,canvas.width,canvas.height);
  
  // Draw grid
  for(let y=0;y<ROWS;y++){
    for(let x=0;x<COLS;x++){
      drawCell(x,y,grid[y][x]);
    }
  }
  
  // Draw current piece
  if(current){
    for(let y=0;y<current.shape.length;y++){
      for(let x=0;x<current.shape[y].length;x++){
        if(current.shape[y][x]){
          drawCell(current.x+x,current.y+y,current.color);
        }
      }
    }
  }
  
  // Game over overlay
  if(gameOver){
    ctx.fillStyle='rgba(0,0,0,0.75)';
    ctx.fillRect(0,0,canvas.width,canvas.height);
    ctx.fillStyle='white';
    ctx.font='24px sans-serif';
    ctx.textAlign='center';
    ctx.fillText('GAME OVER',canvas.width/2,canvas.height/2);
    ctx.font='16px sans-serif';
    ctx.fillText('Press R to restart',canvas.width/2,canvas.height/2+30);
  }
}

// Check collision
function collides(piece,dx=0,dy=0){
  for(let y=0;y<piece.shape.length;y++){
    for(let x=0;x<piece.shape[y].length;x++){
      if(piece.shape[y][x]){
        const newX=piece.x+x+dx;
        const newY=piece.y+y+dy;
        if(newX<0||newX>=COLS||newY>=ROWS||
          (newY>=0&&grid[newY][newX])){
          return true;
        }
      }
    }
  }
  return false;
}

// Merge piece to grid
function merge(){
  for(let y=0;y<current.shape.length;y++){
    for(let x=0;x<current.shape[y].length;x++){
      if(current.shape[y][x]){
        const py=current.y+y;
        const px=current.x+x;
        if(py>=0){
          grid[py][px]=current.color;
        }
      }
    }
  }
}

// Clear lines
function clearLines(){
  let cleared=0;
  for(let y=ROWS-1;y>=0;y--){
    if(grid[y].every(cell=>cell)){
      grid.splice(y,1);
      grid.unshift(Array(COLS).fill(0));
      cleared++;
      y++;
    }
  }
  
  if(cleared){
    lines+=cleared;
    score+=[40,100,300,1200][cleared-1]*level;
    level=Math.floor(lines/10)+1;
    dropTime=Math.max(100,1000-level*90);
    updateDisplay();
  }
}

// Rotate piece
function rotate(){
  const rotated=current.shape[0].map((_,i)=>
    current.shape.map(row=>row[i]).reverse()
  );
  const prev=current.shape;
  current.shape=rotated;
  if(collides(current)){
    current.shape=prev;
  }
}

// Update display
function updateDisplay(){
  scoreEl.textContent=score;
  linesEl.textContent=lines;
  levelEl.textContent=level;
}

// Move piece
function move(dx,dy){
  if(!collides(current,dx,dy)){
    current.x+=dx;
    current.y+=dy;
    return true;
  }
  return false;
}

// Drop piece
function drop(){
  if(!move(0,1)){
    merge();
    clearLines();
    current=spawn();
    if(collides(current)){
      gameOver=true;
    }
  }
}

// Hard drop
function hardDrop(){
  while(move(0,1)){}
  drop();
}

// Game loop
function gameLoop(time=0){
  if(!gameOver&&time-lastDrop>dropTime){
    drop();
    lastDrop=time;
  }
  draw();
  requestAnimationFrame(gameLoop);
}

// Controls
document.addEventListener('keydown',e=>{
  if(gameOver){
    if(e.key==='r'||e.key==='R'){
      init();
    }
    return;
  }
  
  switch(e.key){
    case'ArrowLeft':move(-1,0);break;
    case'ArrowRight':move(1,0);break;
    case'ArrowDown':drop();break;
    case'ArrowUp':rotate();break;
    case' ':hardDrop();break;
  }
  draw();
});

// Start game
init();
gameLoop();
})();
</script>
</body>
</html>`;

const BASIC_TYPESCRIPT = `/**
 * Generated TypeScript template
 */

export class GeneratedService {
  constructor(private name: string = "Generated") {}

  async process(data: any): Promise<any> {
    console.log(\`Processing in \${this.name}\`);
    // TODO: Implement your logic here
    return { success: true, data };
  }

  validate(input: unknown): boolean {
    return input != null;
  }
}

export default GeneratedService;`;

const BASIC_JAVASCRIPT = `/**
 * Generated JavaScript template
 */

class GeneratedModule {
  constructor(name = "Generated") {
    this.name = name;
  }

  async process(data) {
    console.log(\`Processing in \${this.name}\`);
    // TODO: Implement your logic here
    return { success: true, data };
  }

  validate(input) {
    return input != null;
  }
}

module.exports = GeneratedModule;`;
