name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'NPM tag (alpha, beta, latest)'
        required: true
        default: 'alpha'
        type: choice
        options:
          - alpha
          - beta
          - latest

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Publish to npm
        run: |
          npm publish --access public --tag ${{ github.event.inputs.tag || 'alpha' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release Notes
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const version = require('./package.json').version;
            const tag = context.payload.inputs?.tag || 'alpha';
            
            const body = `
            ## 🎉 MARIA CODE v${version} (${tag}) Published!
            
            ### Installation
            \`\`\`bash
            npm install -g @bonginkan/maria@${tag}
            \`\`\`
            
            ### Quick Start
            \`\`\`bash
            maria
            # or
            mc
            \`\`\`
            
            ### What's New
            See [CHANGELOG.md](https://github.com/bonginkan/maria/blob/main/CHANGELOG.md) for details.
            
            ### Support
            - Website: https://bonginkan.ai/
            - Email: info@bonginkan.ai
            - Issues: https://github.com/bonginkan/maria/issues
            
            ---
            Built with ❤️ by Bonginkan Inc.
            `;
            
            console.log(body);